name: pull request

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  syntax-checks:
    runs-on: ${{ vars.RUNNER_LINUX_X64_4 || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v7
      - run: make install
      - run: make awesome_lint
      - run: make export_markdown
